name: clean_provider_architecture
description: "A new Flutter project."
version: 2025.0.1+2025.0.1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # Firebase
  cloud_firestore: ^5.6.3
  cloud_functions: ^5.3.2
  firebase_analytics: ^11.4.2
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_crashlytics: ^4.3.2
  # Networking
  http: ^1.2.2
  url_launcher: ^6.0.10
  # State Management
  provider: ^6.1.2
  # UI
  simple_circular_progress_bar: ^1.0.2
  cached_network_image: ^3.3.1
  cached_video_player_plus: ^3.0.3
  camera: ^0.11.1
  chewie: ^1.8.3
  country_flags: ^3.2.0
  extended_text_field: ^16.0.0
  flutter_cached_pdfview: ^0.4.2
  flutter_chat_ui: ^1.6.15
  flutter_image_compress: ^2.3.0
  flutter_markdown: ^0.7.6+2
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  flutter_typeahead: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.1
  google_maps_cluster_manager_2: ^3.2.0
  modal_bottom_sheet: ^3.0.0
  photo_view: ^0.15.0
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  signature: ^5.4.0
  scrollable_positioned_list: ^0.3.8
  video_player: ^2.8.7
  # Utils
  health: ^12.0.1

  flutter_kronos_plus: ^1.0.0+1
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  social_share: ^2.3.1
  screenshot: ^3.0.0
  after_layout: ^1.2.0
  app_links: ^6.3.0
  elegant_notification: ^2.4.0
  collection: ^1.18.0
  crypto: ^3.0.3
  easy_debounce: ^2.0.3
  file_picker: ^8.0.6
  flutter_dotenv: ^5.1.0
  flutter_gen: ^5.7.0
  flutter_launcher_icons: ^0.14.3
  flutter_stripe: ^11.0.0
  geolocator: ^13.0.2
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  just_audio: ^0.9.40
  location: ^8.0.0
  mime: any
  path_provider: ^2.1.3
  permission_handler: ^11.0.0
  visibility_detector: ^0.4.0+2
  pull_to_refresh_flutter3: ^2.0.2
  photo_manager: ^3.1.1
  record: ^5.1.2
  video_thumbnail: ^0.5.3
  widget_to_marker: ^1.0.6
  flutter_chat_types: any
  path: any
  vector_graphics: any
  scroll_to_index: any
  flutter_parsed_text: any
dev_dependencies:
  build_runner: any
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: any
flutter_gen:
  line_length: 120
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
  fonts:
    enabled: true
    outputs:
      class_name: Fonts
  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/colors.xml
flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: "assets/fonts/Inter_28pt-Thin.ttf"
          weight: 300
        - asset: "assets/fonts/Inter_28pt-Light.ttf"
          weight: 400
        - asset: "assets/fonts/Inter_28pt-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Inter_28pt-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Inter_28pt-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Inter_28pt-ExtraBold.ttf"
          weight: 800
    - family: SFPro
      fonts:
        - asset: "assets/fonts/SF-Pro-Display-Ultralight.otf"
          weight: 200
        - asset: "assets/fonts/SF-Pro-Display-Light.otf"
          weight: 300
        - asset: "assets/fonts/SF-Pro-Display-Regular.otf"
          weight: 400
        - asset: "assets/fonts/SF-Pro-Display-Medium.otf"
          weight: 500
        - asset: "assets/fonts/SF-Pro-Display-Semibold.otf"
          weight: 600
        - asset: "assets/fonts/SF-Pro-Display-Bold.otf"
          weight: 700
        - asset: "assets/fonts/SF-Pro-Display-Heavy.otf"
          weight: 800

  assets:
    - config.env
    - assets/
    - assets/fonts/
    - assets/images/
